title: Aphra
subtitle: A simple sitebuilder in Perl
description: Aphra is a simple sitebuilder written in Perl.
author: Dave Cross

ga4: G-BPYX8N4NQJ

nav:
  - link: /
    text: Home
  - link: /documentation/
    text: Documentation
